* Dictionary
** Profile
A general and convenient concept for realizing rollbacks.
** Database
/nix/var/nix/db/db.sqlite

Keeps track of the dependencies between derivations.

Made up of multiple "generations".
* Operator
Boolean - ||, &&, !, builtins.div.
Relational - !=, ==, <, >, <=, >=.
e1 // e2 - e2 shadows values from e1
* Type
Simple types:
 * Integer
 * Floating point
 * String
 * Path
 * Boolean
 * Null
Complex types:
 * List
 * Set
s = { foo = "bar"; a-b = "str"; "key" = "value"; }
Access key/value: s.a-b
   * Argument set
mul = { a, b }
   * Recursive set
rec { a = "val"; b = "val"; }
** Function
*** if
*** let
Define local variables for inner expression.
*** with
Include includes attrribute set into expression.
*** lambda
**** One argument
x: x*2
**** Several arguments
y: (x: x*y)
**** Variadic arguments
mul = { a, b, ... }: a*b
* Different notes
** stdenvNoCC
without C compiler
** Check what closure references
#+begin_src shell
nix-store -q --references path/
#+end_src
* Built-in function
currentSystem
isAttrs
attrNames
toString
* removeReferencesTo
Forces remove of the dependency. Even if Nix filter does not reduce dependency after compilation.
* Useful commands
** Show direct runtime dependencies
#+begin_src shell
nix-store -q --references "$(command -v bassename)"
#+end_src

** Show reverse dependencies
#+begin_src shell
nix-store -q --referrers "$(command -v basename)"
#+end_src

** Show catamorphed closure
#+begin_src shell
nix-store -qR "$(command -v bassename)"
#+end_src

** Show tree of closure
#+begin_src shell
nix-store -q --tree "$(command -v basename)"
#+end_src

** Recovering making rollback from store directory
#+begin_src shell
/nix/store/<hash>-nix-<ver>/bin/nix-env --rollback
#+end_src

** Recover with reinstall from store directory
#+begin_src shell
/nix/store/<hash>-nix-<ver>/bin/nix-env -i /nix/store/<hash>-nix-<ver>
#+end_src

** Show all derivation dependencies sorted by their closure size
#+begin_src shell
nix path-info --json -rS *store path* | jq 'map(select(.closureSize > 1e6)) | sort_by(.closureSize) | map([.path, .closureSize/1e6])'
#+end_src
** Show all derivation dependencies sorted by their output size
#+begin_src shell
nix path-info --json -rs *store path* | jq 'map(select(.narSize > 1e6)) | sort_by(.narSize) | map([.path, .narSize/1e6])'
#+end_src
** Show all closure dependencies in a tree form
#+begin_src shell
nix-store -q --tree *store path*
#+end_src
** Build derivation from local NixPkgs description
#+begin_src shell
nix-build {/home/pyro/src/nixpkgs} -A *attrName*
#+end_src
** Get total closure size
#+begin_src shell
nix-store -qR *store path* | xargs du -s | cut -f 1 | xargs | sed -e 's/ /+/g'|bc
#+end_src
** Enter nix-shell environment to test/work with package
#+begin_src shell
nix-shell {/home/pyro/src/nixpkgs} -A *attrName*
#+end_src
As comands enter next phases:
*** unpackPhase
*** cd *folder*
*** patchPhase
*** configurePhase
*** buildPhase
** Build depending closures with nox-review
#+begin_src shell
nix-shell -p nox --run "nox-review wip"    # tests uncommited changes
nix-shell -p nox --run "nox-review wip --against *the previous to changes commit*"
nix-shell -p nox --run "nox-review pr *id*"    # very slow, clones NixPkgs
#+end_src
** Run tests for package
For current system <nixpkgs>, using NIX_PATH:
#+begin_src shell
nix-build '<nixpkgs/nixos/tests/login.nix>'
#+end_src

For running selected nix derivation / test from Git NixPkgs repo:
#+begin_src shell
cd ~/src/nixpkgs/..
nix-build test.nix
#+end_src

It runs against the current Git repo.
** To try the app without installing
   #+begin_src shell
   nix run nixpkgs.nix-review
   #+end_src
* Developing/debugging package
** Set: enableParallelBuilding -> false, - so log output would be syncronized
** Write-down initial size of closure with: nix path-info -S /nix/store/hash-package
** Sort the dependencies in the end, as last changes
** Before writing bug reports: dig deeper, think broadly
** Run nix-shell -p nox --run "nox-review wip --against <commithash>" to test-build dependent packages.
** Run tests before submitting pull request with cd path_to_test ;and nix-build <test-file.nix>
** Debug flags for make (put it in buildFlags section)
make --debug=FLAGS

where flags can be:

    a for all debugging (same as make -d and make --debug).
    b for basic debugging.
    v for slightly more verbose basic debugging.
    i for implicit rules.
    j for invocation information.
    m for information during makefile remakes.

** Build isolation on Hydra
Sandboxing allows to solve cuncerrect bind of the same port on several build packages tests.

NixOS now has default: sandboxes enabled.

It is possible to enable sandboxing on Multiuser installations of Nix.

Sandboxing has OS API similar to container APIs (like, Docker).

Sandbox is strict.
** Sandbox components
  * (No cgroups, cgroups is to limit how much resources process can use)
*** Build chroot
#+begin_src shell
/
 build/
       env-vars/
       projectName/
 usr/bin/env
 bin/sh
 etc/
     group
     hosts
     passwd
 proc/..
 dev/..
 nix/store/ # Build closure <-Bind-mount-[ Host Nix store ]
#+end_src
*** Sandbox namespacing
  * Network namespacing - private loopback device
  * IPC namespacing - private unix sockets/shared memory
  * UTS namespacing - private hostname: `localhost`
  * User namespacing - single user `nixbld`:1000 -Mapped-onto-> one of `nixbld`:[1-99] on the host
  * Mount namespacing - bind mounts limited to chroot
  * PID namespacing - build sees only its own processes
*** Seccomp
  * System call filter
  * Policy programs based on eBPF-vm
  * Forbids setuid binaries
  * Forbids ACL
** breakpointHook buildInputs
When the build crashes - it halts and print a command that allows to attach to the buildbox.
It attaches your system attached to the sandbox.

To go fully into the container:
#+begin_src shell
cntr exec
#+end_src
** Debug syscalls with sysdig
See [[nix-sysdig]]
* Evaluating data in REPL
#+begin_src shell
nix repl
pkgs = import <nixpkgs> {}
pkgs.config.allowUnfree
#-> true
#+end_src
* Utils
** Define Nix dependencies to build in nix-shell env with `nix-script` tool
** Nix-review tool to automate reviews
** niff - compares two Nix expressions and determines which attributes changed
** nix-sysdig
Debug the build, record system call trace, replay it.

`sysdig` is a Kernel tool to debug containers.
Inside the Kernel there is a `sysdig.ko`.
Kernel -> sysgig.ko -> System call trace -> sysdig

Use the wrapper `nix-sysdig`:
  * Records all system calls
  * Replay system calls on demand with filtering
  * + Add heuristics
#+begin_src shell
sudo nix-sysdig record packageName
# shell now in the package sandboxe
# manually go through the procedure to build the package
Ctrl+C - stop recording
#+end_src
* Features :drill:
:PROPERTIES:
:ID:       a92f03d4-52a5-42d5-ad45-f9ebe1c4c067
:END:
** Profiles are snapshots :drill:
:PROPERTIES:
:ID:       dd7e0293-0bd5-4ce8-ba39-394b96d1d0db
:END:
They provide rollback versioning.
** Language is purely funcitonal, with lazy evaluation. :drill:
:PROPERTIES:
:ID:       44d92141-78f1-4505-89b0-565fd57edcc0
:END:
** Everything in Nix language is an expression
** Everything is immutable
** Strongly typed, not statically typed (must do conversions to match types)
* Shortcommings :drill:
:PROPERTIES:
:ID:       ae2225e0-9322-4e9b-b506-cb79f34ee69f
:END:
*** Data format migration is your own responsibility
*** Nix on Linux uses it's own stack of everything
* Misc
** Sharing /nix over all nodes
* Internals
:PROPERTIES:
:ID:       569bb267-d7c9-468a-ad1d-c9086d5f4b55
:END:
** Nix uses SQLite
** ~/.nix-profile/ -> /nix/var/nix/profiles/per-user/<uname>/profile
* Tools
** Main tools
*** nix-env
Manages environment, profiles and their generations.
List generations:
#+begin_src fish
/*/ --list-generations
#+end_src

List installed derivations:
#+begin_src fish
/*/ --querry
#+end_src

Rollback:
#+begin_src fish
/*/ --rollback
#+end_src

Switch to generation:
#+begin_src fish
/*/ --switch-generation <num>
#+end_src

Upgrade:
#+begin_src fish
/*/ --upgrade <packages>
/*/ --upgrade    # Everything
#+end_src

Remove:
#+begin_src fish
/*/ --uninstall <package>
/*/ --uninstall '.*'    # Everything
#+end_src

Freeze the package to hold-back, keep the current version:
#+begin_src fish
/*/ --set-flag keep true package
#+end_src

Make package a priority, to solve filename clashes:
#+begin_src fish
/*/ --set-flag priority <lower_number> package
/*/ --set-flag priority 5 binutils
/*/ --set-flag priority 10 gcc
#+end_src

*** nix-repl
Read-eval-print-loop for work with Nix language.
*** nix-store
Querrying store & closures.

References (immidiate depedencies):
#+begin_src fish
/*/ --querry --references <paths>
#+end_src

Referrers (the store paths currently existing in the store that refer to one of paths):
#+begin_src fish
/*/ --querry --refererrers <paths>
#+end_src

Whole closure of referrers:
#+begin_src fish
/*/ --querry --refererrers-closure <paths>
#+end_src

Requisites (the whole closure of dependencies):
#+begin_src fish
/*/ --querry --requisites <paths>
#+end_src

=stdout= serialized data prepared for import from the store
(if =paths= refer to not includded paths - import probably would fail, for proper export see: [[nix-copy-closure]]):
#+begin_src fish
/*/ --export <paths>
#+end_src

=stdout= serialized data prepared for import to the store
(if =stdin= refers to not included | not existing path - would fail):
#+begin_src fish
/*/ --import
#+end_src

Print in the tree form, bigger closures first, recurse into paths only uniqule:
#+begin_src fish
/*/ --tree
#+end_src
*** nix-build
Build a nix expresiion.
